export const DEFAULT_NODE_DATE_FORMAT = 'YYYY-MM-DD';
export const DEFAULT_INVOICE_NUMBER_FORMAT = '<<YYYY>>/<<SERIAL3>>';
export const DEFAULT_RECEIPT_NUMBER_FORMAT = '<<YYYY>>/RCT/<<SERIAL3>>';
export const DEFAULT_PAYMENT_NUMBER_FORMAT = '<<YYYY>>/PAY/<<SERIAL3>>';
export const DEFAULT_JOURNAL_NUMBER_FORMAT = '<<FISCAL_START_YY>>-<<FISCAL_END_YY>>/<<SERIAL1>>';
export const DEFAULT_AUTOCOMPLETE_SEARCH_DEBOUNCE_MS = 250;
